### ISSUE TITLE
Rewrite the page with React.

### ISSUE THREAD

**Issue by MKrupauskas** [MKrupauskas/mkrupauskas.github.io#1]
You can start with create-react-app

**Comment by lyvwhyr** [comment]
/request
I would like to work on this one

**Comment by MKrupauskas** [comment]
@feralCode hey, go ahead! :)

**Comment by justintucker** [comment]
@MKrupauskas Are you still looking to have this done?

**Comment by MKrupauskas** [comment]
@justintucker thanks for the ping, this is no longer needed. :) There's a [new project](https://github.com/mkrupauskas/personal-website) now.
